### ISSUE TITLE
I can not send commands to Siri

### ISSUE THREAD

**Issue by fparrav** [lombardi-zz/ppm#2]
The plugin works seamlessly with the application compatible with homekit, I put the pin on the console and can change channels, and control the volume. But I can not give instructions through siri. I do not know what kind of device or as siri tell that this is a tv, or if it is a problem of language (Spanish).

Greetings from Chile.

**Comment by lombardi-zz** [comment]
You must use the Eve App and create Scene´s. Siri don't understand Channel or Volume.

Example:
1. Switch the Channel on Remote Controller
2. Let display the channel on overview or Channel (Kanal)
3. Go to Automatisation <= German 
4. Create Scene like BBC or other with the selected Channel

**Comment by fparrav** [comment]
Thanks, scenes work correctly, but strangely if I set Siri in English could send commands like turn off or on the tv without creating a scene for that.
My other question is whether there is a way to configure the channels for Digital Mode (antenna ISDB-Tb in my case) instead of analog (cable).

**Comment by lombardi-zz** [comment]
Please Test "tv:dvbc" or "tv:dvbt".
